export const de = {
  htmlLang: 'de', hreflang: 'de-DE', prefix: 'de', languageName: 'Deutsch', shortLanguage: 'DE', legalLocale: 'de',
  nav: { blocker: 'App-Blocker', how: 'So funktioniert’s', privacy: 'Datenschutz', faq: 'FAQ', download: 'Zone laden', menu: 'Menü öffnen', language: 'Sprache', home: 'Startseite' },
  common: { appStore: 'Im App Store laden', learnMore: 'So blockiert Zone Ablenkungen', available: 'Für iPhone und iPad · Erfordert iOS 18 oder neuer', kicker: 'Zone für iPhone und iPad', footerText: 'Striktes Blockieren von Apps und Websites für geschützte Fokuszeit.', product: 'Produkt', guides: 'Ratgeber', company: 'Informationen', legalPolicy: 'Vollständige Datenschutzerklärung', copyright: '© 2026 Vikas Saini. Alle Rechte vorbehalten.', appleNote: 'Apple, iPhone, iPad, Bildschirmzeit, Dynamic Island und Live Activities sind Marken von Apple Inc.', skipContent: 'Zum Inhalt springen', primaryNavigation: 'Hauptnavigation', screenTimeGuide: 'Bildschirmzeit-Alternative', doomscrollingGuide: 'Doomscrolling stoppen', press: 'Presse', webAnalytics: ['Website-Analytics', 'Diese Website nutzt Cloudflare Web Analytics, um Besuche, verweisende Websites, Länder, Geräte und Leistung zusammengefasst zu verstehen. Laut Cloudflare erhebt oder nutzt der Dienst keine personenbezogenen Besucherdaten und verwendet weder Cookies noch localStorage. Das ist von der Zone-App getrennt, die keine Drittanbieter-Analytics enthält.'], onThisPage: 'Auf dieser Seite', related: 'Passender Ratgeber', ctaTitle: 'Die nächste Stunde gehört dir.', ctaBody: 'Wähle deine Blockierungen, starte den Timer und gib deiner Aufmerksamkeit ein klares Ziel.', factsOnly: 'Produktangaben basieren auf der aktuellen Version von Zone.' },
  home: {
    metaTitle: 'Zone — Strikter App- und Website-Blocker fürs iPhone', metaDescription: 'Blockiere ablenkende Apps und Websites während Fokus-Sitzungen. Zone ist ein strikter, privater Fokus-Timer für iPhone und iPad.', eyebrow: 'Strikter Fokus mit Absicht', title: 'Schalte den Lärm aus.', titleAccent: 'Komm in deine Zone.', intro: 'Zone ist ein Fokus-Timer, der ablenkende Apps und Websites auf iPhone und iPad blockiert – damit aus einem Impuls keine Stunde Scrollen wird.', secondaryCta: 'So funktioniert die Blockierung', proofOneTitle: 'Strikter Modus', proofOneBody: 'Macht das Abbrechen einer Sitzung schwerer', proofTwoTitle: 'Standardmäßig privat', proofTwoBody: 'Kein Konto. Deine Auswahl bleibt privat.', signals: [['Apps + Websites', 'Beides in einer Sitzung blockieren'], ['Strikter Modus', 'Mehr Hürde, wenn Willenskraft nachlässt'], ['Live Activities', 'Restzeit ohne Öffnen von Zone sehen'], ['Privates Design', 'Kein Konto und kein Werbe-Tracking']],
    featureLabel: 'Ablenkungen blockieren', featureTitle: 'Ein Timer, der verändert, was dein Handy tun kann.', featureIntro: 'Gewöhnliche Timer zählen Minuten. Zone verbindet den Countdown mit echten Einschränkungen und schützt so deine geplante Fokuszeit.', blockerTitle: 'Wähle die Ablenkungen', blockerBody: 'Bestimme Apps und Website-Kategorien, die nicht verfügbar sein sollen. Zone kann die konkreten Elemente deiner Auswahl nicht sehen.', timerTitle: 'Wähle deine Zeit', timerBody: 'Starte eine voreingestellte oder eigene Sitzung und sieh die Restzeit in Zone, auf dem Sperrbildschirm oder in Dynamic Island.', strictTitle: 'Schaffe echte Verbindlichkeit', strictBody: 'Der Strikte Modus ist für den Moment gedacht, in dem du eine Sitzung vorzeitig beenden möchtest.', strictRows: ['App- und Website-Sperre', 'Flexible Fokus-Timer', 'Optionaler Strikter Modus'], privacyTitle: 'Fokus ohne Überwachung', privacyBody: 'Zone erfüllt seine Aufgabe, ohne ein Werbeprofil über deine Aufmerksamkeit zu erstellen.', privacyPoints: ['Kein Konto', 'Keine Drittanbieter-Analytics', 'Private Auswahl', 'Dein Verlauf bleibt deiner'],
    flowLabel: 'So funktioniert’s', flowTitle: 'Drei Schritte von der Absicht zum Fokus.', flow: [['Auswählen', 'Wähle Apps und Websites, die dich häufig ablenken.'], ['Festlegen', 'Bestimme die Dauer und aktiviere bei Bedarf den Strikten Modus.'], ['Fokussieren', 'Zone setzt die Einschränkungen um und zeigt die Restzeit.']], insightLabel: 'Deinen Einsatz sehen', insightTitle: 'Mach aus Fokusminuten ein verständliches Muster.', insightIntro: 'Sieh Sitzungen, Fokuszeit, Serien und blockierte Versuche. Abgeschlossene Sitzungen können optional als Mindful Minutes in Apple Health gespeichert werden.', insightRows: [['Sitzungsverlauf', 'Sieh, wann und wie lange du fokussiert warst.'], ['Serien und Insights', 'Erkenne Beständigkeit ohne neue Ablenkung.'], ['Optional Apple Health', 'Speichere Sitzungen als Mindful Minutes.']], quote: 'Dein Handy sollte die Entscheidung schützen, die du bereits getroffen hast – statt sie immer wieder zu verlangen.', quoteBy: 'Die Idee hinter Zone', timerAlt: 'Laufender Zone Fokus-Timer auf einem iPhone', appPickerAlt: 'Auswahl zu blockierender Apps in Zone', insightsAlt: 'Insights zu Fokus-Sitzungen in Zone', faqLabel: 'Schnelle Antworten', faqTitle: 'Vor dem Start einer Sitzung', faqIntro: 'Die praktischen Details, die du zuerst wissen möchtest.'
  },
  faqs: [
    ['Was blockiert Zone?', 'Zone kann ausgewählte Apps und Websites während einer aktiven Sitzung einschränken. Apples Bildschirmzeit-Frameworks setzen die Einschränkungen auf dem Gerät um.'],
    ['Kann Zone meine ausgewählten Apps oder Websites sehen?', 'Nein. Apple stellt Zone eine undurchsichtige Auswahl bereit. Die App kann sie anwenden, ohne die konkreten Apps oder Websites zu kennen.'],
    ['Kann ich eine Sitzung vorzeitig beenden?', 'Normale Sitzungen lassen sich beenden. Der Strikte Modus macht diese Entscheidung schwieriger; nutze ihn nur, wenn du dich auf die gewählte Dauer festlegen möchtest.'],
    ['Braucht Zone ein Konto?', 'Nein. Du kannst Zone ohne Konto verwenden.'],
    ['Welche Geräte werden unterstützt?', 'Zone läuft auf kompatiblen iPhones und iPads mit iOS oder iPadOS 18 oder neuer.'],
    ['Funktioniert Zone mit Apple Health?', 'Optional. Mit deiner Erlaubnis kann Zone abgeschlossene Sitzungen als Mindful Minutes speichern.'],
    ['Ist Zone eine Suchtbehandlung?', 'Nein. Zone ist ein Produktivitätswerkzeug, das Ablenkungen erschwert; es ist keine medizinische Behandlung.']
  ],
  articles: {
    blocker: { metaTitle: 'Strikter App- und Website-Blocker fürs iPhone — Zone', metaDescription: 'So blockiert Zone Apps und Websites während zeitlich begrenzter Sitzungen auf iPhone und iPad – optional mit Striktem Modus.', eyebrow: 'App- und Website-Blocker', title: 'Rücke Ablenkungen für eine Weile außer Reichweite.', intro: 'Zone kombiniert einen Fokus-Timer mit App- und Website-Einschränkungen. Du entscheidest, was blockiert wird, wie lange und ob der Strikte Modus aktiv ist.', sections: [
      { id: 'what', title: 'Was Zone blockiert', paragraphs: ['Zone kann ausgewählte Apps und Websites während einer Sitzung abschirmen. Wähle soziale Feeds, Videos, Shopping, Nachrichten oder andere Optionen aus Apples Auswahlansicht.'], bullets: ['Ausgewählte iPhone- und iPad-Apps', 'Ausgewählte Websites und Kategorien', 'Als Voreinstellung gespeicherte Kombinationen'] },
      { id: 'how', title: 'So funktioniert die Blockierung auf dem iPhone', paragraphs: ['Zone nutzt Apples Bildschirmzeit-Frameworks. Das System liefert eine undurchsichtige Darstellung deiner Auswahl. So kann Zone sie anwenden, ohne die konkreten Elemente zu kennen.', 'Nach Ablauf des Timers entfernt Zone die Einschränkungen. Die App muss weder deinen Browserverlauf lesen noch beobachten, welche Apps du öffnest.'] },
      { id: 'strict', title: 'Was der Strikte Modus ändert', paragraphs: ['Der Strikte Modus schafft Verbindlichkeit und erschwert bewusst ein vorzeitiges Ende. Für flexible Sitzungen lässt du ihn ausgeschaltet.'], callout: ['Bewusst verwenden', 'Beginne mit einer realistischen Dauer und steigere sie erst, wenn der Ablauf zu dir passt.'] },
      { id: 'setup', title: 'Einfache Einrichtung', steps: ['Wähle ablenkende Apps und Websites.', 'Lege die Dauer fest.', 'Entscheide über den Strikten Modus.', 'Starte und lass Zone im Hintergrund laufen.'] },
      { id: 'privacy', title: 'Blockieren ohne Liste deiner Gewohnheiten', paragraphs: ['Zone sieht deine konkrete Auswahl nicht. Kein Konto ist nötig und es gibt keine Drittanbieter-Analytics. Auswahl und Fokusverlauf bleiben privat.'] }
    ] },
    screenTime: { metaTitle: 'Eine fokussierte Alternative zu Apple Bildschirmzeit — Zone', metaDescription: 'Vergleiche Zone mit Apple Bildschirmzeit für zeitgesteuertes Blockieren, Website-Sperren und den Strikten Modus.', eyebrow: 'Bildschirmzeit-Alternative', title: 'Bildschirmzeit ist umfassend. Zone ist für eine Fokus-Sitzung gebaut.', intro: 'Bildschirmzeit bündelt Nutzungsberichte, Limits und Familienfunktionen. Zone nutzt Apples Frameworks für eine engere Aufgabe: einen fokussierten Zeitraum zu schützen.', sections: [
      { id: 'difference', title: 'Der praktische Unterschied', paragraphs: ['Nutze Bildschirmzeit für allgemeine Limits, Auszeit, Inhalte oder Familie. Nutze Zone, wenn du Ablenkungen auswählen, einen Timer starten und jetzt fokussieren möchtest.'], comparison: [['Bedarf', 'Zone', 'Bildschirmzeit'], ['Zeitlich begrenzte Sitzungen', 'Zentraler Ablauf', 'Über Limits und Zeitpläne'], ['Ausgewählte Sperren', 'Pro Sitzung', 'Pro Limit oder Zeitplan'], ['Strikte Verbindlichkeit', 'Optionaler Strikter Modus', 'Andere Codes und Kontrollen'], ['Auswertung', 'Sitzungen und blockierte Versuche', 'Allgemeine Gerätenutzung']] },
      { id: 'choose', title: 'Wann Zone besser passt', bullets: ['Du willst einen klaren Start- und Endpunkt.', 'Blocker und Countdown sollen zusammengehören.', 'Du willst Voreinstellungen für Arbeit, Lernen oder Ruhe.', 'Du willst die Restzeit in Live Activities oder Dynamic Island sehen.'] },
      { id: 'together', title: 'Du kannst beides verwenden', paragraphs: ['Zone ersetzt nicht jede Bildschirmzeit-Funktion. Behalte langfristige Limits und nutze Zone für bewusst gestartete Fokus-Sitzungen.'] },
      { id: 'accurate', title: 'Auf Apples Kontrollen aufgebaut', paragraphs: ['Zone hängt vom genehmigten Zugriff und Apples unterstützten Frameworks ab. Die App umgeht iOS nicht und verspricht keine technisch unmögliche Sperre.'] }
    ] },
    doomscrolling: { metaTitle: 'Doomscrolling auf dem iPhone stoppen — Praktischer Ratgeber', metaDescription: 'Ein praktischer Ratgeber gegen Doomscrolling auf dem iPhone: Auslöser ändern, Hürden schaffen und zeitweise blockieren.', eyebrow: 'Praktischer Fokus-Ratgeber', title: 'Verlass dich beim Aufhören nicht nur auf Willenskraft.', intro: 'Doomscrolling beginnt oft automatisch: entsperren, tippen, aktualisieren. Der beste Eingriff passiert, bevor diese Schleife Fahrt aufnimmt.', sections: [
      { id: 'pattern', title: 'Mach die Schleife sichtbar', paragraphs: ['Achte auf den Auslöser, nicht nur auf die Gesamtzeit. Vielleicht öffnest du einen Feed nach einer schwierigen Aufgabe, in Übergängen, im Bett oder nach einer Mitteilung.', 'Notiere einen Tag lang, was direkt vorher passiert. Eine kurze Auslöserliste hilft mehr als Selbstkritik über eine Wochenzahl.'] },
      { id: 'friction', title: 'Baue vor dem ersten Wischen eine Hürde ein', bullets: ['Entferne auslösende Apps vom ersten Home-Bildschirm.', 'Schalte nicht dringende Mitteilungen aus.', 'Melde dich von automatisch geöffneten Diensten ab.', 'Nutze zu vorhersehbaren Zeiten einen Timer-Blocker.'], callout: ['Warum Hürden helfen', 'Du verbietest Ablenkung nicht für immer. Du gibst der bewussten Entscheidung Zeit, den automatischen Impuls einzuholen.'] },
      { id: 'window', title: 'Schütze zuerst ein kleines Zeitfenster', paragraphs: ['Beginne mit 20 Minuten Lesen, 30 Minuten Arbeit oder den ersten 45 Minuten am Morgen. Blockiere in Zone nur das, was dieses Fenster gefährdet, und nutze den Strikten Modus nur für zusätzliche Verbindlichkeit.'] },
      { id: 'replace', title: 'Gib dem Impuls ein anderes Ziel', paragraphs: ['Blockieren entfernt eine Option, bestimmt aber nicht die nächste. Lege Dokument, Buch oder Aufgabe sichtbar bereit, bevor du startest.'] },
      { id: 'review', title: 'Bewerte das Muster, nicht deinen Wert', paragraphs: ['Prüfe am Wochenende, welche Zeitfenster funktioniert haben, und passe Umgebung oder Dauer an. Das ist eine Gestaltungsfrage, kein Charakterurteil.', 'Wenn die Nutzung gefährlich wird oder stark belastet, ersetzt eine Produktivitäts-App keine qualifizierte professionelle Hilfe.'] }
    ] },
    faq: { metaTitle: 'Zone FAQ — Blockierung, Strikter Modus und Datenschutz', metaDescription: 'Antworten zu App- und Website-Sperren, Striktem Modus, Datenschutz, Live Activities und Apple Health.', eyebrow: 'Häufige Fragen', title: 'Klare Antworten, bevor du Ablenkungen blockierst.', intro: 'Wie Zone funktioniert, worauf die App zugreifen kann und was während einer Sitzung passiert.', sections: [] },
    privacy: { metaTitle: 'Zone Datenschutz — Blockieren ohne Konto', metaDescription: 'Verständliche Übersicht zu Blockierauswahl, Fokusverlauf, Apple Health, iCloud und Live-Activity-Daten.', eyebrow: 'Datenschutzübersicht', title: 'Deine Fokusentscheidungen sollten deine bleiben.', intro: 'Zone blockiert Ablenkungen, ohne deine private Liste ausgewählter Apps und Websites zu kennen.', sections: [
      { id: 'summary', title: 'Kurz gesagt', bullets: ['Kein Konto erforderlich.', 'Zone sieht die konkret ausgewählten Apps und Websites nicht.', 'Fokusverlauf und Auswahl bleiben privat.', 'Keine Drittanbieter-Analytics oder Werbetracker in der App.'] },
      { id: 'screen-time', title: 'Bildschirmzeit-Auswahl', paragraphs: ['Apple liefert Zone undurchsichtige Token. Damit setzt die App Einschränkungen um, ohne dass diese Token deine Auswahl dem Entwickler offenlegen.'] },
      { id: 'health', title: 'Apple Health', paragraphs: ['Das Speichern als Mindful Minutes ist optional. Zone fragt nur nach Zugriff, wenn du die Funktion aktivierst; die Erlaubnis bleibt in iOS unter deiner Kontrolle.'] },
      { id: 'icloud', title: 'Privater iCloud-Sync', paragraphs: ['Zone Sync speichert deinen Fokusverlauf und unterstützte Einstellungen nur in deinem privaten iCloud-Account. Zone sendet diese Sync-Daten nicht an einen externen Server. So kannst du Daten nach einer Neuinstallation wiederherstellen und auf Geräten mit demselben Apple Account verwenden.'] },
      { id: 'live', title: 'Live Activities', paragraphs: ['Bei aktivierten Remote-Updates sendet Zone nur APNs-Token und den minimal nötigen Timer-Status. Deine App- und Website-Auswahl wird nicht gesendet.'] },
      { id: 'policy', title: 'Vollständige Erklärung lesen', paragraphs: ['Diese verständliche Übersicht ersetzt nicht die rechtliche Datenschutzerklärung. Das bereits veröffentlichte Dokument bleibt maßgeblich.'], link: ['Vollständige Datenschutzerklärung öffnen', 'legal'] }
    ] },
    press: { metaTitle: 'Zone Pressekit — Produktdaten und offizielle Screenshots', metaDescription: 'Genaue Produktdaten, App-Store-Link, Entwicklerangaben und offizielle Materialien zu Zone.', eyebrow: 'Presse und Reviews', title: 'Die wichtigsten Fakten zu Zone.', intro: 'Eine kurze und verlässliche Quelle für Medien, Reviewer und Creator.', sections: [
      { id: 'summary', title: 'Produktübersicht', paragraphs: ['Zone: App Blocker & Focus ist eine Produktivitäts-App für iPhone und iPad des unabhängigen Entwicklers Vikas Saini. Anders als ein reiner Timer kann Zone ausgewählte Apps und Websites für die Dauer einer Fokus-Session sperren. Der optionale Strikte Modus erhöht die Verbindlichkeit; Live Activities, Dynamic Island und private Insights helfen dabei, konzentriert zu bleiben.'] },
      { id: 'facts', title: 'Kurzdaten', facts: [['Produkt', 'Zone: App Blocker & Focus'], ['Entwickler', 'Vikas Saini'], ['Plattformen', 'iPhone und iPad'], ['Voraussetzung', 'iOS oder iPadOS 18 oder neuer'], ['Kategorie', 'Produktivität'], ['Konto', 'Nicht erforderlich']] },
      { id: 'angles', title: 'Was Zone unterscheidet', bullets: ['Timer und Blocker funktionieren als eine gemeinsame Session.', 'Der Strikte Modus schafft gezielt Hürden, wenn sich eine Session nicht leicht abbrechen lassen soll.', 'Apple stellt undurchsichtige Auswahlen bereit: Zone und der Entwickler sehen die konkreten Apps oder Websites nicht.', 'Live Activities und Dynamic Island halten den Countdown sichtbar, ohne die App erneut zu öffnen.'] },
      { id: 'assets', title: 'Offizielle Materialien', paragraphs: ['Icon und lokalisierte Screenshots dürfen für eine sachliche Berichterstattung oder Review verwendet werden. Das Icon nicht verändern oder Unterstützung vortäuschen.'], downloads: [['App-Icon', 'app-icon.png'], ['Timer-Screenshot', 'timer.png'], ['Screenshot der App-Auswahl', 'app-picker.png'], ['Insights-Screenshot', 'insights.png']], downloadLabel: 'PNG herunterladen', link: ['Zone im App Store ansehen', 'appstore'] },
      { id: 'contact', title: 'Kontakt', paragraphs: ['Für Produktfragen, Testzugang, Interviews oder Presse kontaktiere den Entwickler direkt.'], emailLabel: 'E-Mail an den Entwickler' }
    ] },
    contact: { metaTitle: 'Zone kontaktieren — Support, Feedback und Presse', metaDescription: 'Kontaktiere den unabhängigen Zone-Entwickler für Support, Vorschläge, Feedback, Reviews oder Presseanfragen.', eyebrow: 'Zone kontaktieren', title: 'Eine Frage, ein Vorschlag oder Feedback?', intro: 'Kontaktiere den unabhängigen Entwickler von Zone für Support, Vorschläge, Reviews, Presse oder andere produktbezogene Anliegen.', sections: [
      { id: 'email', title: 'E-Mail an Zone', paragraphs: ['Sende deine Nachricht an die folgende Adresse. Die Nachrichten werden vom Entwickler gelesen; die Antwortzeit kann variieren.'], emailLabel: 'E-Mail senden' },
      { id: 'helpful-details', title: 'Hilfreiche Angaben für den Support', paragraphs: ['Bei einem technischen Problem erleichtern einige relevante Angaben die Untersuchung.'], bullets: ['iPhone- oder iPad-Modell', 'iOS- oder iPadOS-Version', 'Version der Zone-App', 'Was du erwartet hast und was stattdessen geschah'] },
      { id: 'privacy-note', title: 'Vor dem Senden', paragraphs: ['Sende keine Passwörter, Zahlungsdaten oder andere besonders sensiblen Informationen. Teile Angaben zu Blockierauswahl oder Fokusverlauf nur, wenn sie relevant sind und du dich damit wohlfühlst.'] }
    ] }
  }
};
