export const es = {
  htmlLang: 'es', hreflang: 'es-ES', prefix: 'es', languageName: 'Español (España)', shortLanguage: 'ES', legalLocale: 'es',
  nav: { blocker: 'Bloqueador', how: 'Cómo funciona', privacy: 'Privacidad', faq: 'Preguntas', download: 'Obtener Zone', menu: 'Abrir menú', language: 'Idioma', home: 'Inicio' },
  common: {
    appStore: 'Descargar en el App Store', learnMore: 'Descubre cómo bloquea Zone', available: 'Para iPhone y iPad · Requiere iOS 18 o posterior', kicker: 'Zone para iPhone y iPad',
    footerText: 'Bloqueo estricto de apps y sitios web para proteger tu concentración.', product: 'Producto', guides: 'Guías', company: 'Información', legalPolicy: 'Política de privacidad completa',
    copyright: '© 2026 Vikas Saini. Todos los derechos reservados.', appleNote: 'Apple, iPhone, iPad, Tiempo de uso, Dynamic Island y Live Activities son marcas de Apple Inc.',
    skipContent: 'Saltar al contenido', primaryNavigation: 'Navegación principal', screenTimeGuide: 'Alternativa a Tiempo de uso', doomscrollingGuide: 'Frenar el doomscrolling', press: 'Prensa', onThisPage: 'En esta página', related: 'Guía relacionada', ctaTitle: 'Haz tuya la próxima hora.', ctaBody: 'Elige qué bloquear, inicia el temporizador y dale a tu atención un único destino.', factsOnly: 'La información corresponde a la versión actual de Zone.'
  },
  home: {
    metaTitle: 'Zone — Bloqueador estricto de apps y webs para iPhone', metaDescription: 'Bloquea apps y sitios web durante sesiones de concentración. Zone es un temporizador estricto y privado para iPhone y iPad.',
    eyebrow: 'Concentración estricta, por diseño', title: 'Apaga el ruido.', titleAccent: 'Entra en tu zona.', intro: 'Zone es un temporizador que bloquea apps y sitios web en tu iPhone y iPad, para que un impulso no se convierta en una hora de scroll.', secondaryCta: 'Ver cómo funciona',
    proofOneTitle: 'Modo estricto', proofOneBody: 'Hace más difícil abandonar una sesión', proofTwoTitle: 'Privado por defecto', proofTwoBody: 'Sin cuenta. Tus selecciones son privadas.',
    signals: [['Apps + sitios web', 'Bloquea ambos en una sesión'], ['Modo estricto', 'Añade fricción cuando falla la voluntad'], ['Live Activities', 'Consulta el tiempo sin abrir Zone'], ['Diseño privado', 'Sin cuenta ni rastreo publicitario']],
    featureLabel: 'Bloqueo de distracciones', featureTitle: 'Un temporizador que cambia lo que puede hacer tu móvil.', featureIntro: 'Un temporizador normal solo cuenta minutos. Zone une la cuenta atrás con restricciones reales para proteger el tiempo que querías dedicar a concentrarte.',
    blockerTitle: 'Elige las distracciones', blockerBody: 'Selecciona las apps y categorías de sitios web que no estarán disponibles. Zone no puede ver los elementos concretos que eliges.',
    timerTitle: 'Elige el tiempo', timerBody: 'Inicia una sesión predefinida o personalizada y consulta el tiempo restante en Zone, la pantalla bloqueada o Dynamic Island.',
    strictTitle: 'Comprométete de verdad', strictBody: 'El Modo estricto está pensado para ese momento en que quieres terminar la sesión antes de tiempo.', strictRows: ['Bloqueo de apps y webs', 'Temporizadores flexibles', 'Modo estricto opcional'],
    privacyTitle: 'Concéntrate sin vigilancia', privacyBody: 'Zone hace su trabajo sin crear un perfil publicitario sobre tu atención.', privacyPoints: ['Sin cuenta', 'Sin analíticas de terceros', 'Selecciones privadas', 'Tu historial sigue siendo tuyo'],
    flowLabel: 'Cómo funciona', flowTitle: 'Tres pasos entre la intención y la concentración.', flow: [['Elige', 'Selecciona las apps y sitios que suelen distraerte.'], ['Comprométete', 'Define la duración y activa el Modo estricto si necesitas más fricción.'], ['Concéntrate', 'Zone aplica las restricciones y mantiene visible el tiempo restante.']],
    insightLabel: 'Observa el esfuerzo', insightTitle: 'Convierte tus minutos de concentración en un patrón comprensible.', insightIntro: 'Revisa sesiones, tiempo concentrado, rachas e intentos bloqueados. También puedes guardar sesiones completadas en Apple Health como Mindful Minutes.',
    insightRows: [['Historial de sesiones', 'Consulta cuándo y cuánto tiempo te concentraste.'], ['Rachas y estadísticas', 'Observa tu constancia sin añadir ruido.'], ['Apple Health opcional', 'Guarda sesiones como Mindful Minutes si quieres.']],
    quote: 'Tu teléfono debería proteger la decisión que ya tomaste, no obligarte a tomarla una y otra vez.', quoteBy: 'La idea detrás de Zone', timerAlt: 'Temporizador de concentración de Zone en un iPhone', appPickerAlt: 'Selección de apps para bloquear en Zone', insightsAlt: 'Estadísticas de sesiones de concentración en Zone', faqLabel: 'Respuestas rápidas', faqTitle: 'Antes de iniciar una sesión', faqIntro: 'Los detalles prácticos que normalmente quieres saber primero.'
  },
  faqs: [
    ['¿Qué bloquea Zone?', 'Zone puede restringir las apps y sitios web seleccionados mientras una sesión está activa. Los frameworks de Tiempo de uso de Apple aplican las restricciones en el dispositivo.'],
    ['¿Puede Zone ver qué apps o webs selecciono?', 'No. Apple entrega a Zone selecciones opacas, por lo que puede aplicar tus elecciones sin saber qué apps o sitios concretos has elegido.'],
    ['¿Puedo terminar una sesión antes?', 'Las sesiones normales se pueden finalizar. El Modo estricto hace esa decisión más difícil; úsalo solo si estás dispuesto a respetar la duración elegida.'],
    ['¿Zone necesita una cuenta?', 'No. Puedes usar Zone sin crear una cuenta.'],
    ['¿Qué dispositivos son compatibles?', 'Zone funciona en iPhone y iPad compatibles con iOS o iPadOS 18 o posterior.'],
    ['¿Funciona con Apple Health?', 'Opcionalmente. Si das permiso, Zone puede guardar las sesiones completadas como Mindful Minutes.'],
    ['¿Zone es un tratamiento para la adicción?', 'No. Zone es una herramienta de productividad que añade fricción ante las distracciones; no es un tratamiento médico.']
  ],
  articles: {
    blocker: { metaTitle: 'Bloqueador estricto de apps y webs para iPhone — Zone', metaDescription: 'Descubre cómo Zone bloquea apps y sitios web durante sesiones temporizadas en iPhone y iPad, con Modo estricto opcional.', eyebrow: 'Bloqueador de apps y webs', title: 'Pon las distracciones fuera de alcance durante un rato.', intro: 'Zone combina un temporizador con restricciones de apps y sitios web. Tú decides qué bloquear, durante cuánto tiempo y si activas el Modo estricto.', sections: [
      { id: 'what', title: 'Qué bloquea Zone', paragraphs: ['Zone puede ocultar las apps y sitios web seleccionados mientras una sesión está activa. Elige las distracciones que importan en tu caso: redes sociales, vídeo, compras, noticias u otras opciones disponibles en la interfaz de Apple.'], bullets: ['Apps seleccionadas de iPhone y iPad', 'Sitios web y categorías seleccionados', 'Combinaciones guardadas como ajustes reutilizables'] },
      { id: 'how', title: 'Cómo funciona el bloqueo en iPhone', paragraphs: ['Zone utiliza los frameworks de Tiempo de uso de Apple. El sistema entrega una representación opaca de tus elecciones, por lo que Zone puede aplicar el bloqueo sin conocer las apps o webs concretas.', 'Cuando termina el temporizador, Zone retira las restricciones de la sesión. No necesita leer tu historial de navegación ni vigilar las apps que abres.'] },
      { id: 'strict', title: 'Qué cambia el Modo estricto', paragraphs: ['El Modo estricto añade compromiso y hace deliberadamente más difícil abandonar una sesión antes de tiempo. Para sesiones más flexibles, déjalo desactivado.'], callout: ['Úsalo de forma consciente', 'Empieza con una duración realista y aumenta el tiempo solo cuando el hábito te funcione.'] },
      { id: 'setup', title: 'Configuración sencilla', steps: ['Elige las apps y webs que te distraen.', 'Selecciona una duración.', 'Decide si necesitas el Modo estricto.', 'Inicia la sesión y deja Zone en segundo plano.'] },
      { id: 'privacy', title: 'Bloqueo sin una lista de tus hábitos', paragraphs: ['Zone no puede ver tus selecciones concretas. No requiere cuenta ni incorpora analíticas de terceros. Tus elecciones y tu historial de concentración siguen siendo privados.'] }
    ] },
    screenTime: { metaTitle: 'Una alternativa a Tiempo de uso centrada en sesiones — Zone', metaDescription: 'Compara Zone con Tiempo de uso de Apple para bloquear apps y webs en sesiones con temporizador y Modo estricto.', eyebrow: 'Alternativa a Tiempo de uso', title: 'Tiempo de uso es amplio. Zone está hecho para una sesión.', intro: 'Tiempo de uso reúne informes, límites y controles familiares. Zone usa los frameworks de Apple para una tarea más concreta: proteger un bloque de concentración.', sections: [
      { id: 'difference', title: 'La diferencia práctica', paragraphs: ['Usa Tiempo de uso para límites generales, Tiempo de inactividad, contenido o familia. Usa Zone cuando quieras elegir distracciones, iniciar un temporizador y concentrarte ahora.'], comparison: [['Necesidad', 'Zone', 'Tiempo de uso'], ['Sesiones temporizadas', 'Flujo principal', 'Mediante límites y horarios'], ['Bloqueo seleccionado', 'Por sesión', 'Por límite u horario'], ['Compromiso estricto', 'Modo estricto opcional', 'Códigos y controles diferentes'], ['Informes', 'Sesiones e intentos bloqueados', 'Actividad general del dispositivo']] },
      { id: 'choose', title: 'Cuándo encaja mejor Zone', bullets: ['Quieres un ritual claro de inicio y fin.', 'Quieres bloqueo y cuenta atrás juntos.', 'Quieres ajustes distintos para trabajo, estudio o descanso.', 'Quieres ver el tiempo en Live Activities o Dynamic Island.'] },
      { id: 'together', title: 'Puedes usar ambos', paragraphs: ['Zone no sustituye todas las funciones de Tiempo de uso. Mantén límites a largo plazo y usa Zone para sesiones deliberadas.'] },
      { id: 'accurate', title: 'Basado en los controles de Apple', paragraphs: ['Zone depende del acceso que apruebes y de los frameworks compatibles de Apple. No evita iOS ni promete un bloqueo imposible para el sistema.'] }
    ] },
    doomscrolling: { metaTitle: 'Cómo dejar el doomscrolling en iPhone — Guía práctica', metaDescription: 'Guía práctica para reducir el doomscrolling en iPhone cambiando señales, añadiendo fricción y usando bloqueo temporizado.', eyebrow: 'Guía práctica de concentración', title: 'Deja de depender de la fuerza de voluntad para parar el scroll.', intro: 'El doomscrolling suele empezar con una acción automática: desbloquear, tocar, actualizar. La mejor intervención ocurre antes de que el bucle gane velocidad.', sections: [
      { id: 'pattern', title: 'Haz visible el patrón', paragraphs: ['Observa la señal, no solo el total de horas. Quizá abras un feed después de una tarea difícil, entre actividades, en la cama o tras una notificación.', 'Durante un día, apunta qué ocurre justo antes de abrir la app. Una lista breve de desencadenantes ayuda más que culparte por el total semanal.'] },
      { id: 'friction', title: 'Añade fricción antes del primer gesto', bullets: ['Quita las apps más tentadoras de la primera pantalla.', 'Desactiva notificaciones que no sean urgentes.', 'Cierra sesión en servicios que abres sin pensar.', 'Usa un bloqueo temporizado en los momentos previsibles.'], callout: ['Por qué ayuda', 'No intentas prohibir la distracción para siempre. Creas el tiempo necesario para que la elección consciente alcance al impulso.'] },
      { id: 'window', title: 'Protege primero un intervalo pequeño', paragraphs: ['Empieza con un bloque que puedas terminar: 20 minutos de lectura, 30 de trabajo o los primeros 45 minutos del día. En Zone, bloquea solo lo que rompe ese intervalo y activa el Modo estricto únicamente si quieres ese compromiso.'] },
      { id: 'replace', title: 'Da al impulso otro destino', paragraphs: ['Bloquear elimina una opción, pero no elige la siguiente. Deja a la vista la tarea, el documento o el libro antes de empezar.'] },
      { id: 'review', title: 'Revisa el patrón, no tu valor personal', paragraphs: ['Al final de la semana, revisa qué intervalos funcionaron y ajusta el entorno o la duración. Es un problema de diseño, no un juicio sobre ti.', 'Si el uso te causa peligro o malestar grave, una app de productividad no sustituye la ayuda profesional cualificada.'] }
    ] },
    faq: { metaTitle: 'Preguntas de Zone — Bloqueo, Modo estricto y privacidad', metaDescription: 'Respuestas sobre bloqueo de apps y webs, Modo estricto, privacidad, Live Activities y Apple Health en Zone.', eyebrow: 'Preguntas frecuentes', title: 'Respuestas claras antes de bloquear distracciones.', intro: 'Cómo funciona Zone, a qué puede acceder y qué ocurre durante una sesión.', sections: [] },
    privacy: { metaTitle: 'Privacidad de Zone — Bloqueo sin cuenta', metaDescription: 'Resumen claro de cómo Zone trata las selecciones, el historial, Apple Health, iCloud y los datos de Live Activities.', eyebrow: 'Resumen de privacidad', title: 'Tus decisiones de concentración deben seguir siendo tuyas.', intro: 'Zone bloquea distracciones sin conocer la lista privada de apps y sitios web que has elegido.', sections: [
      { id: 'summary', title: 'En pocas palabras', bullets: ['No necesitas cuenta.', 'Zone no puede ver las apps o webs concretas que seleccionas.', 'Tu historial y selecciones siguen siendo privados.', 'La app no incluye analíticas de terceros ni rastreadores publicitarios.'] },
      { id: 'screen-time', title: 'Selecciones de Tiempo de uso', paragraphs: ['Apple entrega a Zone identificadores opacos. La app puede aplicar restricciones, pero esos identificadores no revelan tus elecciones al desarrollador.'] },
      { id: 'health', title: 'Apple Health', paragraphs: ['Guardar sesiones como Mindful Minutes es opcional. Zone pide acceso solo si activas la función y puedes controlarlo desde los ajustes de iOS.'] },
      { id: 'icloud', title: 'Sincronización privada con iCloud', paragraphs: ['Zone Sync guarda tu historial de concentración y las preferencias compatibles solo en tu cuenta privada de iCloud. Zone no envía estos datos a un servidor externo. Te permite restaurarlos al reinstalar Zone y mantenerlos disponibles en dispositivos con la misma cuenta de Apple.'] },
      { id: 'live', title: 'Live Activities', paragraphs: ['Si activas las actualizaciones remotas, Zone envía el token de APNs y el estado mínimo del temporizador necesario. No envía tu selección de apps o webs.'] },
      { id: 'policy', title: 'Lee la política completa', paragraphs: ['Este resumen no sustituye a la política legal. La política ya publicada sigue siendo el documento oficial.'], link: ['Abrir la política de privacidad completa', 'legal'] }
    ] },
    press: { metaTitle: 'Kit de prensa de Zone — Datos y capturas oficiales', metaDescription: 'Datos del producto, enlace al App Store, información del desarrollador y recursos descargables de Zone.', eyebrow: 'Prensa y reseñas', title: 'Los datos esenciales sobre Zone.', intro: 'Una referencia breve y precisa para medios, reseñadores y creadores.', sections: [
      { id: 'summary', title: 'Resumen del producto', paragraphs: ['Zone: App Blocker & Focus es una app de productividad para iPhone y iPad del desarrollador independiente Vikas Saini. Une sesiones temporizadas, bloqueo de apps y webs, Modo estricto, Live Activities y estadísticas privadas.'] },
      { id: 'facts', title: 'Datos rápidos', facts: [['Producto', 'Zone: App Blocker & Focus'], ['Desarrollador', 'Vikas Saini'], ['Plataformas', 'iPhone y iPad'], ['Requisito', 'iOS o iPadOS 18 o posterior'], ['Categoría', 'Productividad'], ['Cuenta', 'No es necesaria']] },
      { id: 'angles', title: 'Qué distingue a Zone', bullets: ['Temporizador y bloqueo forman un solo flujo.', 'El Modo estricto añade compromiso.', 'Las selecciones son opacas para la app.', 'Live Activities mantiene visible la cuenta atrás.'] },
      { id: 'assets', title: 'Recursos oficiales', paragraphs: ['El icono y las capturas localizadas pueden usarse al informar o reseñar Zone con exactitud. No modifiques el icono ni insinúes un respaldo.'], link: ['Ver Zone en el App Store', 'appstore'] },
      { id: 'contact', title: 'Contacto', paragraphs: ['Para preguntas, reseñas o prensa, usa el canal de soporte enlazado en la ficha del App Store.'] }
    ] }
  }
};

export const esMX = {
  ...es,
  htmlLang: 'es-MX', hreflang: 'es-MX', prefix: 'es-mx', languageName: 'Español (México)', shortLanguage: 'MX', legalLocale: 'es-mx',
  home: { ...es.home, metaTitle: 'Zone — Bloqueador estricto de apps y sitios para iPhone', intro: 'Zone es un temporizador que bloquea apps y sitios web en tu iPhone y iPad, para que un impulso no se convierta en una hora de scroll.' }
};
