export const fr = {
  htmlLang: 'fr', hreflang: 'fr-FR', prefix: 'fr', languageName: 'Français', shortLanguage: 'FR', legalLocale: 'fr',
  nav: { blocker: 'Bloqueur', how: 'Fonctionnement', privacy: 'Confidentialité', faq: 'Questions', download: 'Obtenir Zone', menu: 'Ouvrir le menu', language: 'Langue', home: 'Accueil' },
  common: { appStore: 'Télécharger dans l’App Store', learnMore: 'Découvrir le blocage Zone', available: 'Pour iPhone et iPad · Nécessite iOS 18 ou ultérieur', kicker: 'Zone pour iPhone et iPad', footerText: 'Blocage strict des apps et sites web pour protéger votre concentration.', product: 'Produit', guides: 'Guides', company: 'Informations', legalPolicy: 'Politique complète', copyright: '© 2026 Vikas Saini. Tous droits réservés.', appleNote: 'Apple, iPhone, iPad, Temps d’écran, Dynamic Island et Live Activities sont des marques d’Apple Inc.', skipContent: 'Aller au contenu', primaryNavigation: 'Navigation principale', screenTimeGuide: 'Alternative à Temps d’écran', doomscrollingGuide: 'Arrêter le doomscrolling', press: 'Presse', webAnalytics: ['Mesure d’audience du site', 'Ce site utilise Cloudflare Web Analytics pour comprendre de façon agrégée les visites, sites référents, pays, appareils et performances. Cloudflare indique que ce service ne collecte ni n’utilise les données personnelles des visiteurs et n’emploie ni cookies ni localStorage. Il est distinct de l’app Zone, qui n’intègre pas d’analytics tiers.'], onThisPage: 'Sur cette page', related: 'Guide associé', ctaTitle: 'La prochaine heure vous appartient.', ctaBody: 'Choisissez ce que vous bloquez, lancez le minuteur et donnez une seule direction à votre attention.', factsOnly: 'Informations basées sur la version actuelle de Zone.' },
  home: {
    metaTitle: 'Zone — Bloqueur strict d’apps et de sites pour iPhone', metaDescription: 'Bloquez apps et sites web pendant des sessions de concentration. Zone est un minuteur strict et privé pour iPhone et iPad.', eyebrow: 'Concentration stricte par conception', title: 'Coupez le bruit.', titleAccent: 'Entrez dans votre zone.', intro: 'Zone est un minuteur qui bloque les apps et sites web distrayants sur iPhone et iPad, afin qu’une impulsion ne devienne pas une heure de défilement.', secondaryCta: 'Voir comment le blocage fonctionne',
    proofOneTitle: 'Mode strict', proofOneBody: 'Rend une session plus difficile à quitter', proofTwoTitle: 'Privé par défaut', proofTwoBody: 'Aucun compte. Vos choix restent privés.', signals: [['Apps + sites', 'Bloquez les deux dans une session'], ['Mode strict', 'Ajoutez une barrière quand la volonté faiblit'], ['Live Activities', 'Voyez le temps sans rouvrir Zone'], ['Conception privée', 'Sans compte ni suivi publicitaire']],
    featureLabel: 'Blocage des distractions', featureTitle: 'Un minuteur qui change ce que votre téléphone peut faire.', featureIntro: 'Un minuteur ordinaire compte les minutes. Zone associe le compte à rebours à de vraies restrictions pour protéger le temps que vous vouliez consacrer à votre tâche.', blockerTitle: 'Choisissez les distractions', blockerBody: 'Sélectionnez les apps et catégories de sites qui seront indisponibles. Zone ne peut pas voir les éléments précis que vous choisissez.', timerTitle: 'Choisissez la durée', timerBody: 'Lancez une session prédéfinie ou personnalisée et suivez le temps dans Zone, sur l’écran verrouillé ou Dynamic Island.', strictTitle: 'Ajoutez un vrai engagement', strictBody: 'Le Mode strict est conçu pour le moment où vous êtes tenté d’arrêter trop tôt.', strictRows: ['Blocage d’apps et de sites', 'Minuteurs flexibles', 'Mode strict facultatif'], privacyTitle: 'Concentrez-vous sans surveillance', privacyBody: 'Zone remplit sa mission sans créer de profil publicitaire autour de votre attention.', privacyPoints: ['Aucun compte', 'Aucun analytics tiers', 'Sélections privées', 'Votre historique reste le vôtre'],
    flowLabel: 'Fonctionnement', flowTitle: 'Trois étapes entre l’intention et la concentration.', flow: [['Choisissez', 'Sélectionnez les apps et sites qui vous détournent de votre tâche.'], ['Engagez-vous', 'Définissez la durée et activez le Mode strict si nécessaire.'], ['Concentrez-vous', 'Zone applique les restrictions et garde le temps restant visible.']], insightLabel: 'Voyez vos efforts', insightTitle: 'Transformez vos minutes de concentration en tendance lisible.', insightIntro: 'Consultez vos sessions, votre temps de concentration, vos séries et les tentatives bloquées. Vous pouvez aussi enregistrer les sessions dans Apple Health comme Mindful Minutes.', insightRows: [['Historique des sessions', 'Voyez quand et combien de temps vous vous êtes concentré.'], ['Séries et insights', 'Observez votre régularité sans ajouter du bruit.'], ['Apple Health facultatif', 'Enregistrez les sessions comme Mindful Minutes si vous le souhaitez.']], quote: 'Votre téléphone devrait protéger la décision déjà prise, pas vous demander de la reprendre sans cesse.', quoteBy: 'L’idée derrière Zone', timerAlt: 'Minuteur de concentration Zone sur un iPhone', appPickerAlt: 'Sélection des apps à bloquer dans Zone', insightsAlt: 'Insights des sessions de concentration dans Zone', faqLabel: 'Réponses rapides', faqTitle: 'Avant de lancer une session', faqIntro: 'Les détails pratiques que l’on souhaite généralement connaître.'
  },
  faqs: [
    ['Que bloque Zone ?', 'Zone peut restreindre les apps et sites web sélectionnés pendant une session. Les frameworks Temps d’écran d’Apple appliquent les restrictions sur l’appareil.'],
    ['Zone peut-il voir mes sélections ?', 'Non. Apple fournit des sélections opaques : Zone peut les appliquer sans connaître les apps ou sites précis que vous avez choisis.'],
    ['Puis-je arrêter une session plus tôt ?', 'Une session normale peut être arrêtée. Le Mode strict rend ce choix plus difficile ; utilisez-le uniquement si vous acceptez la durée choisie.'],
    ['Faut-il créer un compte ?', 'Non. Vous pouvez utiliser Zone sans compte.'],
    ['Quels appareils sont compatibles ?', 'Zone fonctionne sur les iPhone et iPad compatibles sous iOS ou iPadOS 18 ou ultérieur.'],
    ['Zone fonctionne-t-il avec Apple Health ?', 'Oui, de façon facultative. Avec votre autorisation, Zone peut enregistrer les sessions terminées comme Mindful Minutes.'],
    ['Zone est-il un traitement contre l’addiction ?', 'Non. Zone est un outil de productivité qui ajoute une barrière aux distractions ; ce n’est pas un traitement médical.']
  ],
  articles: {
    blocker: { metaTitle: 'Bloqueur strict d’apps et de sites pour iPhone — Zone', metaDescription: 'Découvrez comment Zone bloque apps et sites pendant des sessions minutées sur iPhone et iPad, avec Mode strict facultatif.', eyebrow: 'Bloqueur d’apps et de sites', title: 'Mettez les distractions hors de portée pour un moment.', intro: 'Zone associe minuteur et restrictions d’apps et de sites. Vous choisissez quoi bloquer, pendant combien de temps et si le Mode strict est nécessaire.', sections: [
      { id: 'what', title: 'Ce que Zone bloque', paragraphs: ['Zone peut masquer les apps et sites sélectionnés pendant une session. Choisissez les distractions importantes pour vous : réseaux sociaux, vidéo, shopping, actualités ou toute option proposée par l’interface d’Apple.'], bullets: ['Apps iPhone et iPad sélectionnées', 'Sites web et catégories sélectionnés', 'Combinaisons enregistrées comme préréglages'] },
      { id: 'how', title: 'Comment fonctionne le blocage sur iPhone', paragraphs: ['Zone utilise les frameworks Temps d’écran d’Apple. Le système fournit une représentation opaque de vos choix : Zone applique le blocage sans connaître les éléments précis.', 'À la fin du minuteur, les restrictions de la session sont retirées. Zone n’a pas besoin de lire votre historique de navigation ni de surveiller les apps ouvertes.'] },
      { id: 'strict', title: 'Ce que change le Mode strict', paragraphs: ['Le Mode strict ajoute un engagement et rend volontairement plus difficile l’abandon anticipé. Pour une session flexible, laissez-le désactivé.'], callout: ['À utiliser consciemment', 'Commencez par une durée réaliste et augmentez-la seulement si ce rythme vous convient.'] },
      { id: 'setup', title: 'Configuration simple', steps: ['Choisissez les apps et sites qui vous distraient.', 'Définissez la durée.', 'Décidez si le Mode strict est utile.', 'Lancez la session et laissez Zone en arrière-plan.'] },
      { id: 'privacy', title: 'Bloquer sans dresser la liste de vos habitudes', paragraphs: ['Zone ne peut pas voir vos sélections précises. Aucun compte n’est requis et l’app n’intègre pas d’analytics tiers. Vos choix et votre historique restent privés.'] }
    ] },
    screenTime: { metaTitle: 'Une alternative ciblée à Temps d’écran — Zone', metaDescription: 'Comparez Zone et Temps d’écran d’Apple pour les sessions minutées, le blocage d’apps et de sites et le Mode strict.', eyebrow: 'Alternative à Temps d’écran', title: 'Temps d’écran est général. Zone est conçu pour une session.', intro: 'Temps d’écran réunit rapports, limites et contrôles familiaux. Zone utilise les frameworks d’Apple pour une mission plus ciblée : protéger un temps de concentration.', sections: [
      { id: 'difference', title: 'La différence concrète', paragraphs: ['Utilisez Temps d’écran pour des limites générales, Temps d’arrêt, le contenu ou la famille. Utilisez Zone pour choisir les distractions, lancer un minuteur et vous concentrer maintenant.'], comparison: [['Besoin', 'Zone', 'Temps d’écran'], ['Sessions minutées', 'Fonction centrale', 'Via limites et horaires'], ['Blocage sélectionné', 'Par session', 'Par limite ou horaire'], ['Engagement strict', 'Mode strict facultatif', 'Codes et contrôles distincts'], ['Rapports', 'Sessions et tentatives bloquées', 'Activité générale de l’appareil']] },
      { id: 'choose', title: 'Quand Zone est plus adapté', bullets: ['Vous voulez un rituel clair de début et de fin.', 'Vous voulez le blocage et le compte à rebours ensemble.', 'Vous voulez différents préréglages pour le travail ou l’étude.', 'Vous voulez suivre le temps dans Live Activities ou Dynamic Island.'] },
      { id: 'together', title: 'Vous pouvez utiliser les deux', paragraphs: ['Zone ne remplace pas toutes les fonctions de Temps d’écran. Gardez des limites à long terme et utilisez Zone pour des sessions volontaires.'] },
      { id: 'accurate', title: 'Construit sur les contrôles Apple', paragraphs: ['Zone dépend des autorisations accordées et des frameworks pris en charge par Apple. Il ne contourne pas iOS et ne promet pas un verrouillage impossible à appliquer.'] }
    ] },
    doomscrolling: { metaTitle: 'Comment arrêter le doomscrolling sur iPhone — Guide pratique', metaDescription: 'Un guide pratique pour réduire le doomscrolling sur iPhone en changeant les déclencheurs et en ajoutant un blocage minuté.', eyebrow: 'Guide pratique de concentration', title: 'Ne comptez plus uniquement sur votre volonté pour arrêter de défiler.', intro: 'Le doomscrolling commence souvent par un geste automatique : déverrouiller, toucher, actualiser. Le meilleur moment pour agir est avant que la boucle ne prenne de l’élan.', sections: [
      { id: 'pattern', title: 'Rendez la boucle visible', paragraphs: ['Repérez le déclencheur, pas seulement le total d’heures. Vous ouvrez peut-être un fil après une tâche difficile, entre deux activités, au lit ou après une notification.', 'Pendant une journée, notez ce qui se passe juste avant. Une courte liste de déclencheurs est plus utile que de vous reprocher un total hebdomadaire.'] },
      { id: 'friction', title: 'Ajoutez une barrière avant le premier geste', bullets: ['Retirez les apps tentantes du premier écran.', 'Désactivez les notifications non urgentes.', 'Déconnectez-vous des services ouverts automatiquement.', 'Utilisez un blocage minuté aux moments prévisibles.'], callout: ['Pourquoi cela aide', 'Vous ne rendez pas la distraction impossible pour toujours. Vous créez le temps nécessaire pour que le choix conscient rattrape l’impulsion.'] },
      { id: 'window', title: 'Protégez d’abord une petite période', paragraphs: ['Commencez par 20 minutes de lecture, 30 minutes de travail ou les 45 premières minutes du matin. Dans Zone, bloquez seulement ce qui menace cette période et activez le Mode strict si vous souhaitez cet engagement.'] },
      { id: 'replace', title: 'Donnez une autre direction à l’impulsion', paragraphs: ['Le blocage retire une option mais ne choisit pas la suivante. Placez le document, le livre ou la tâche en évidence avant de commencer.'] },
      { id: 'review', title: 'Évaluez le schéma, pas votre valeur', paragraphs: ['En fin de semaine, regardez les périodes réussies et ajustez l’environnement ou la durée. C’est un problème de conception, pas un jugement personnel.', 'Si cet usage vous met en danger ou provoque une détresse importante, une app de productivité ne remplace pas une aide professionnelle qualifiée.'] }
    ] },
    faq: { metaTitle: 'FAQ Zone — Blocage, Mode strict et confidentialité', metaDescription: 'Réponses sur le blocage d’apps et de sites, le Mode strict, la confidentialité, Live Activities et Apple Health.', eyebrow: 'Questions fréquentes', title: 'Des réponses claires avant de bloquer les distractions.', intro: 'Comment Zone fonctionne, ce qu’il peut voir et à quoi vous attendre pendant une session.', sections: [] },
    privacy: { metaTitle: 'Confidentialité Zone — Blocage sans compte', metaDescription: 'Résumé clair du traitement des sélections, de l’historique, d’Apple Health, d’iCloud et de Live Activities.', eyebrow: 'Résumé de confidentialité', title: 'Vos choix de concentration doivent rester les vôtres.', intro: 'Zone bloque les distractions sans connaître votre liste privée d’apps et de sites.', sections: [
      { id: 'summary', title: 'En bref', bullets: ['Aucun compte requis.', 'Zone ne voit pas les apps ou sites précis sélectionnés.', 'Votre historique et vos choix restent privés.', 'L’app n’intègre ni analytics tiers ni suivi publicitaire.'] },
      { id: 'screen-time', title: 'Sélections Temps d’écran', paragraphs: ['Apple fournit à Zone des jetons opaques. L’app applique les restrictions, mais ces jetons ne révèlent pas vos choix au développeur.'] },
      { id: 'health', title: 'Apple Health', paragraphs: ['L’enregistrement comme Mindful Minutes est facultatif. Zone demande l’accès uniquement si vous activez cette fonction, et vous gardez le contrôle dans iOS.'] },
      { id: 'icloud', title: 'Synchronisation iCloud privée', paragraphs: ['Zone Sync stocke votre historique de concentration et les préférences prises en charge uniquement dans votre compte iCloud privé. Zone n’envoie pas ces données à un serveur externe. Vous pouvez ainsi les restaurer après une réinstallation et les retrouver sur les appareils utilisant le même compte Apple.'] },
      { id: 'live', title: 'Live Activities', paragraphs: ['Si vous activez les mises à jour distantes, Zone envoie le jeton APNs et l’état minimal du minuteur nécessaire. Votre sélection d’apps et de sites n’est pas envoyée.'] },
      { id: 'policy', title: 'Lire la politique complète', paragraphs: ['Ce résumé ne remplace pas la politique juridique. La politique déjà publiée reste le document officiel.'], link: ['Ouvrir la politique de confidentialité complète', 'legal'] }
    ] },
    press: { metaTitle: 'Kit presse Zone — Informations et captures officielles', metaDescription: 'Informations produit, lien App Store, développeur et ressources officielles pour découvrir et présenter Zone.', eyebrow: 'Presse et tests', title: 'Les informations essentielles sur Zone.', intro: 'Une référence concise et exacte pour les journalistes, testeurs et créateurs.', sections: [
      { id: 'summary', title: 'Résumé du produit', paragraphs: ['Zone: App Blocker & Focus est une app de productivité pour iPhone et iPad créée par le développeur indépendant Vikas Saini. Elle associe sessions minutées, blocage, Mode strict, Live Activities et insights privés.'] },
      { id: 'facts', title: 'Faits rapides', facts: [['Produit', 'Zone: App Blocker & Focus'], ['Développeur', 'Vikas Saini'], ['Plateformes', 'iPhone et iPad'], ['Système', 'iOS ou iPadOS 18 ou ultérieur'], ['Catégorie', 'Productivité'], ['Compte', 'Non requis']] },
      { id: 'angles', title: 'Ce qui distingue Zone', bullets: ['Minuteur et bloqueur dans un même parcours.', 'Le Mode strict ajoute un engagement.', 'Les sélections sont opaques pour l’app.', 'Live Activities garde le compte à rebours visible.'] },
      { id: 'assets', title: 'Ressources officielles', paragraphs: ['L’icône et les captures localisées peuvent servir à couvrir ou tester Zone avec exactitude. Ne modifiez pas l’icône et ne suggérez pas un soutien officiel.'], link: ['Voir Zone dans l’App Store', 'appstore'] },
      { id: 'contact', title: 'Contact', paragraphs: ['Pour toute question, demande de test ou presse, utilisez le canal d’assistance lié depuis l’App Store.'] }
    ] }
  }
};
