export const it = {
  htmlLang: 'it', hreflang: 'it-IT', prefix: 'it', languageName: 'Italiano', shortLanguage: 'IT', legalLocale: 'it',
  nav: { blocker: 'Blocco app', how: 'Come funziona', privacy: 'Privacy', faq: 'Domande', download: 'Scarica Zone', menu: 'Apri menu', language: 'Lingua', home: 'Home' },
  common: { appStore: 'Scarica dall’App Store', learnMore: 'Scopri come Zone blocca le distrazioni', available: 'Per iPhone e iPad · Richiede iOS 18 o successivo', kicker: 'Zone per iPhone e iPad', footerText: 'Blocco rigoroso di app e siti web per proteggere la concentrazione.', product: 'Prodotto', guides: 'Guide', company: 'Informazioni', legalPolicy: 'Informativa completa', copyright: '© 2026 Vikas Saini. Tutti i diritti riservati.', appleNote: 'Apple, iPhone, iPad, Tempo di utilizzo, Dynamic Island e Live Activities sono marchi di Apple Inc.', skipContent: 'Vai al contenuto', primaryNavigation: 'Navigazione principale', screenTimeGuide: 'Alternativa a Tempo di utilizzo', doomscrollingGuide: 'Fermare il doomscrolling', press: 'Stampa', webAnalytics: ['Analisi del sito', 'Questo sito usa Cloudflare Web Analytics per comprendere in forma aggregata visite, siti di provenienza, paesi, dispositivi e prestazioni. Cloudflare dichiara che il servizio non raccoglie né utilizza dati personali dei visitatori e non usa cookie o localStorage. È separato dall’app Zone, che non include analytics di terze parti.'], onThisPage: 'In questa pagina', related: 'Guida correlata', ctaTitle: 'La prossima ora è tua.', ctaBody: 'Scegli cosa bloccare, avvia il timer e dai alla tua attenzione una sola direzione.', factsOnly: 'Le informazioni si basano sulla versione attuale di Zone.' },
  home: {
    metaTitle: 'Zone — Blocco rigoroso di app e siti web per iPhone', metaDescription: 'Blocca app e siti web durante sessioni di concentrazione. Zone è un timer rigoroso e privato per iPhone e iPad.', eyebrow: 'Concentrazione rigorosa, per scelta', title: 'Spegni il rumore.', titleAccent: 'Entra nella tua zona.', intro: 'Zone è un timer che blocca app e siti web distraenti su iPhone e iPad, così un impulso non diventa un’ora di scrolling.', secondaryCta: 'Scopri come funziona il blocco', proofOneTitle: 'Modalità Rigorosa', proofOneBody: 'Rende più difficile abbandonare una sessione', proofTwoTitle: 'Privato per impostazione predefinita', proofTwoBody: 'Nessun account. Le tue scelte restano private.', signals: [['App + siti web', 'Blocca entrambi in una sessione'], ['Modalità Rigorosa', 'Aggiunge attrito quando la volontà cala'], ['Live Activities', 'Vedi il tempo senza riaprire Zone'], ['Design privato', 'Nessun account o tracciamento pubblicitario']],
    featureLabel: 'Blocco delle distrazioni', featureTitle: 'Un timer che cambia ciò che il telefono può fare.', featureIntro: 'I timer comuni contano i minuti. Zone unisce il conto alla rovescia a restrizioni reali per proteggere il tempo che volevi dedicare alla concentrazione.', blockerTitle: 'Scegli le distrazioni', blockerBody: 'Seleziona le app e le categorie di siti che non saranno disponibili. Zone non può vedere gli elementi specifici che scegli.', timerTitle: 'Scegli il tempo', timerBody: 'Avvia una sessione predefinita o personalizzata e segui il tempo in Zone, sulla schermata di blocco o nella Dynamic Island.', strictTitle: 'Crea un impegno reale', strictBody: 'La Modalità Rigorosa è pensata per il momento in cui vorresti terminare troppo presto.', strictRows: ['Blocco di app e siti', 'Timer flessibili', 'Modalità Rigorosa facoltativa'], privacyTitle: 'Concentrati senza sorveglianza', privacyBody: 'Zone fa il suo lavoro senza creare un profilo pubblicitario sulla tua attenzione.', privacyPoints: ['Nessun account', 'Nessuna analisi di terze parti', 'Selezioni private', 'La cronologia resta tua'],
    flowLabel: 'Come funziona', flowTitle: 'Tre passaggi tra intenzione e concentrazione.', flow: [['Scegli', 'Seleziona le app e i siti che tendono a distrarti.'], ['Impegnati', 'Imposta la durata e attiva la Modalità Rigorosa se serve.'], ['Concentrati', 'Zone applica le restrizioni e mantiene visibile il tempo rimanente.']], insightLabel: 'Guarda il tuo impegno', insightTitle: 'Trasforma i minuti concentrati in uno schema comprensibile.', insightIntro: 'Rivedi sessioni, tempo di concentrazione, serie e tentativi bloccati. Puoi anche salvare le sessioni in Apple Health come Mindful Minutes.', insightRows: [['Cronologia delle sessioni', 'Vedi quando e per quanto tempo ti sei concentrato.'], ['Serie e dati', 'Osserva la costanza senza aggiungere rumore.'], ['Apple Health facoltativo', 'Salva le sessioni come Mindful Minutes se vuoi.']], quote: 'Il telefono dovrebbe proteggere la decisione che hai già preso, non chiederti di riprenderla ogni volta.', quoteBy: 'L’idea dietro Zone', timerAlt: 'Timer di concentrazione Zone su un iPhone', appPickerAlt: 'Selezione delle app da bloccare in Zone', insightsAlt: 'Dati sulle sessioni di concentrazione in Zone', faqLabel: 'Risposte rapide', faqTitle: 'Prima di iniziare una sessione', faqIntro: 'I dettagli pratici che di solito vuoi conoscere per primi.'
  },
  faqs: [
    ['Cosa blocca Zone?', 'Zone può limitare le app e i siti web selezionati durante una sessione. I framework Tempo di utilizzo di Apple applicano le restrizioni sul dispositivo.'],
    ['Zone può vedere le app o i siti che scelgo?', 'No. Apple fornisce selezioni opache, quindi Zone può applicarle senza conoscere le app o i siti specifici.'],
    ['Posso terminare una sessione in anticipo?', 'Le sessioni normali possono essere terminate. La Modalità Rigorosa rende più difficile questa scelta; usala solo se accetti la durata selezionata.'],
    ['Serve un account?', 'No. Puoi usare Zone senza creare un account.'],
    ['Quali dispositivi sono supportati?', 'Zone è disponibile per iPhone e iPad compatibili con iOS o iPadOS 18 o successivo.'],
    ['Zone funziona con Apple Health?', 'Facoltativamente. Con il tuo permesso, Zone può salvare le sessioni completate come Mindful Minutes.'],
    ['Zone è un trattamento per la dipendenza?', 'No. Zone è uno strumento di produttività che aggiunge attrito alle distrazioni; non è un trattamento medico.']
  ],
  articles: {
    blocker: { metaTitle: 'Blocco rigoroso di app e siti per iPhone — Zone', metaDescription: 'Scopri come Zone blocca app e siti web durante sessioni a tempo su iPhone e iPad, con Modalità Rigorosa facoltativa.', eyebrow: 'Blocco di app e siti web', title: 'Metti le distrazioni fuori portata per un po’.', intro: 'Zone combina un timer con restrizioni di app e siti. Decidi tu cosa bloccare, per quanto tempo e se usare la Modalità Rigorosa.', sections: [
      { id: 'what', title: 'Cosa blocca Zone', paragraphs: ['Zone può schermare app e siti selezionati durante una sessione. Scegli social, video, shopping, notizie o altre opzioni disponibili nell’interfaccia Apple.'], bullets: ['App selezionate su iPhone e iPad', 'Siti web e categorie selezionati', 'Combinazioni salvate come preset riutilizzabili'] },
      { id: 'how', title: 'Come funziona il blocco su iPhone', paragraphs: ['Zone usa i framework Tempo di utilizzo di Apple. Il sistema fornisce una rappresentazione opaca delle tue scelte, così Zone può applicare il blocco senza conoscere gli elementi specifici.', 'Al termine del timer, Zone rimuove le restrizioni della sessione. Non deve leggere la cronologia web né osservare le app che apri.'] },
      { id: 'strict', title: 'Cosa cambia la Modalità Rigorosa', paragraphs: ['La Modalità Rigorosa aggiunge impegno e rende volutamente più difficile abbandonare una sessione in anticipo. Per maggiore flessibilità, lasciala disattivata.'], callout: ['Usala consapevolmente', 'Inizia con una durata realistica e aumentala solo quando il metodo funziona per te.'] },
      { id: 'setup', title: 'Configurazione semplice', steps: ['Scegli le app e i siti che ti distraggono.', 'Imposta la durata.', 'Decidi se serve la Modalità Rigorosa.', 'Avvia la sessione e lascia Zone in background.'] },
      { id: 'privacy', title: 'Bloccare senza un elenco delle tue abitudini', paragraphs: ['Zone non vede le tue selezioni specifiche. Non richiede un account e non include analytics di terze parti. Scelte e cronologia restano private.'] }
    ] },
    screenTime: { metaTitle: 'Un’alternativa mirata a Tempo di utilizzo — Zone', metaDescription: 'Confronta Zone con Tempo di utilizzo di Apple per sessioni a tempo, blocco di app e siti e Modalità Rigorosa.', eyebrow: 'Alternativa a Tempo di utilizzo', title: 'Tempo di utilizzo è generale. Zone è creato per una sessione.', intro: 'Tempo di utilizzo riunisce report, limiti e controlli famiglia. Zone usa i framework Apple per un compito più mirato: proteggere un intervallo di concentrazione.', sections: [
      { id: 'difference', title: 'La differenza pratica', paragraphs: ['Usa Tempo di utilizzo per limiti generali, Pausa di utilizzo, contenuti o famiglia. Usa Zone quando vuoi scegliere le distrazioni, avviare un timer e concentrarti subito.'], comparison: [['Esigenza', 'Zone', 'Tempo di utilizzo'], ['Sessioni a tempo', 'Flusso principale', 'Con limiti e pianificazioni'], ['Blocco selezionato', 'Per sessione', 'Per limite o orario'], ['Impegno rigoroso', 'Modalità Rigorosa facoltativa', 'Codici e controlli diversi'], ['Report', 'Sessioni e tentativi bloccati', 'Attività generale del dispositivo']] },
      { id: 'choose', title: 'Quando Zone è più adatto', bullets: ['Vuoi un rito chiaro di inizio e fine.', 'Vuoi blocco e conto alla rovescia insieme.', 'Vuoi preset diversi per lavoro, studio o riposo.', 'Vuoi vedere il tempo nelle Live Activities o Dynamic Island.'] },
      { id: 'together', title: 'Puoi usarli entrambi', paragraphs: ['Zone non sostituisce tutte le funzioni di Tempo di utilizzo. Mantieni limiti a lungo termine e usa Zone per sessioni intenzionali.'] },
      { id: 'accurate', title: 'Basato sui controlli Apple', paragraphs: ['Zone dipende dall’accesso che autorizzi e dai framework supportati da Apple. Non aggira iOS e non promette un blocco impossibile da applicare.'] }
    ] },
    doomscrolling: { metaTitle: 'Come smettere di fare doomscrolling su iPhone — Guida', metaDescription: 'Guida pratica per ridurre il doomscrolling su iPhone cambiando i segnali, aggiungendo attrito e usando blocchi a tempo.', eyebrow: 'Guida pratica alla concentrazione', title: 'Non affidarti solo alla forza di volontà per smettere di scorrere.', intro: 'Il doomscrolling spesso inizia con un gesto automatico: sblocca, tocca, aggiorna. Il momento migliore per intervenire è prima che il ciclo acceleri.', sections: [
      { id: 'pattern', title: 'Rendi visibile il ciclo', paragraphs: ['Osserva il segnale, non solo le ore totali. Potresti aprire un feed dopo un compito difficile, durante una pausa, a letto o dopo una notifica.', 'Per un giorno, annota cosa succede appena prima. Un breve elenco di inneschi è più utile che colpevolizzarti per il totale settimanale.'] },
      { id: 'friction', title: 'Aggiungi attrito prima del primo swipe', bullets: ['Rimuovi le app più tentatrici dalla prima schermata.', 'Disattiva le notifiche non urgenti.', 'Esci dai servizi che apri automaticamente.', 'Usa un blocco a tempo nei momenti prevedibili.'], callout: ['Perché aiuta', 'Non stai rendendo impossibile distrarti per sempre. Stai creando il tempo perché la scelta consapevole raggiunga l’impulso.'] },
      { id: 'window', title: 'Proteggi prima un intervallo breve', paragraphs: ['Inizia con 20 minuti di lettura, 30 di lavoro o i primi 45 minuti del mattino. In Zone blocca solo ciò che minaccia quell’intervallo e usa la Modalità Rigorosa solo se vuoi l’impegno extra.'] },
      { id: 'replace', title: 'Dai all’impulso un’altra direzione', paragraphs: ['Bloccare rimuove un’opzione ma non sceglie la successiva. Prepara il documento, il libro o il compito prima di iniziare.'] },
      { id: 'review', title: 'Valuta lo schema, non il tuo valore', paragraphs: ['A fine settimana guarda quali intervalli hanno funzionato e modifica ambiente o durata. È un problema di progettazione, non un giudizio personale.', 'Se l’uso crea pericolo o forte disagio, un’app di produttività non sostituisce un aiuto professionale qualificato.'] }
    ] },
    faq: { metaTitle: 'Domande su Zone — Blocco, Modalità Rigorosa e privacy', metaDescription: 'Risposte su blocco di app e siti, Modalità Rigorosa, privacy, Live Activities e Apple Health.', eyebrow: 'Domande frequenti', title: 'Risposte chiare prima di bloccare le distrazioni.', intro: 'Come funziona Zone, cosa può vedere e cosa aspettarsi da una sessione.', sections: [] },
    privacy: { metaTitle: 'Privacy di Zone — Blocco senza account', metaDescription: 'Panoramica chiara su selezioni, cronologia, Apple Health, iCloud e dati delle Live Activities in Zone.', eyebrow: 'Panoramica sulla privacy', title: 'Le tue scelte di concentrazione devono restare tue.', intro: 'Zone blocca le distrazioni senza conoscere il tuo elenco privato di app e siti.', sections: [
      { id: 'summary', title: 'In breve', bullets: ['Nessun account richiesto.', 'Zone non vede le app o i siti specifici selezionati.', 'Cronologia e scelte restano private.', 'L’app non include analytics di terze parti o tracker pubblicitari.'] },
      { id: 'screen-time', title: 'Selezioni di Tempo di utilizzo', paragraphs: ['Apple fornisce token opachi. Zone li usa per applicare restrizioni, ma non rivelano le tue scelte allo sviluppatore.'] },
      { id: 'health', title: 'Apple Health', paragraphs: ['Salvare le sessioni come Mindful Minutes è facoltativo. Zone chiede l’accesso solo se attivi la funzione e il permesso resta sotto il tuo controllo in iOS.'] },
      { id: 'icloud', title: 'Sincronizzazione iCloud privata', paragraphs: ['Zone Sync salva la cronologia di focus e le preferenze supportate solo nel tuo account iCloud privato. Zone non invia questi dati a un server esterno. Ti consente di ripristinarli dopo una reinstallazione e di averli sui dispositivi con lo stesso account Apple.'] },
      { id: 'live', title: 'Live Activities', paragraphs: ['Se abiliti gli aggiornamenti remoti, Zone invia il token APNs e lo stato minimo del timer necessario. La tua selezione di app e siti non viene inviata.'] },
      { id: 'policy', title: 'Leggi l’informativa completa', paragraphs: ['Questa panoramica non sostituisce l’informativa legale. Il documento già pubblicato resta quello ufficiale.'], link: ['Apri l’informativa sulla privacy completa', 'legal'] }
    ] },
    press: { metaTitle: 'Press kit Zone — Dati e schermate ufficiali', metaDescription: 'Dati accurati, link App Store, informazioni sullo sviluppatore e risorse ufficiali di Zone.', eyebrow: 'Stampa e recensioni', title: 'Le informazioni essenziali su Zone.', intro: 'Un riferimento breve e accurato per giornalisti, recensori e creator.', sections: [
      { id: 'summary', title: 'Riepilogo del prodotto', paragraphs: ['Zone: App Blocker & Focus è un’app di produttività per iPhone e iPad dello sviluppatore indipendente Vikas Saini. A differenza di un semplice timer, Zone può limitare app e siti selezionati durante una sessione. La Modalità Rigorosa facoltativa aumenta l’impegno, mentre Live Activities, Dynamic Island e dati privati aiutano a mantenere la concentrazione.'] },
      { id: 'facts', title: 'Dati rapidi', facts: [['Prodotto', 'Zone: App Blocker & Focus'], ['Sviluppatore', 'Vikas Saini'], ['Piattaforme', 'iPhone e iPad'], ['Requisito', 'iOS o iPadOS 18 o successivo'], ['Categoria', 'Produttività'], ['Account', 'Non richiesto']] },
      { id: 'angles', title: 'Cosa distingue Zone', bullets: ['Timer e blocco funzionano come un’unica sessione.', 'La Modalità Rigorosa aggiunge volutamente attrito quando non dovrebbe essere facile abbandonare una sessione.', 'Apple fornisce selezioni opache: Zone e lo sviluppatore non vedono le app o i siti specifici.', 'Live Activities e Dynamic Island mantengono visibile il conto alla rovescia senza riaprire l’app.'] },
      { id: 'assets', title: 'Risorse ufficiali', paragraphs: ['Icona e schermate localizzate possono essere usate per descrivere o recensire Zone in modo accurato. Non modificare l’icona né suggerire approvazione.'], downloads: [['Icona dell’app', 'app-icon.png'], ['Schermata del timer', 'timer.png'], ['Schermata di selezione app', 'app-picker.png'], ['Schermata dei dati', 'insights.png']], downloadLabel: 'Scarica PNG', link: ['Vedi Zone nell’App Store', 'appstore'] },
      { id: 'contact', title: 'Contatti', paragraphs: ['Per domande sul prodotto, accesso per recensioni, interviste o stampa, contatta direttamente lo sviluppatore.'], emailLabel: 'Scrivi allo sviluppatore' }
    ] },
    contact: { metaTitle: 'Contatta Zone — Supporto, suggerimenti e stampa', metaDescription: 'Contatta lo sviluppatore indipendente di Zone per supporto, suggerimenti, feedback, recensioni o richieste stampa.', eyebrow: 'Contatta Zone', title: 'Hai una domanda, un suggerimento o un commento?', intro: 'Contatta lo sviluppatore indipendente di Zone per supporto, suggerimenti, recensioni, stampa o altre richieste sul prodotto.', sections: [
      { id: 'email', title: 'Scrivi a Zone', paragraphs: ['Invia il messaggio all’indirizzo seguente. I messaggi vengono letti dallo sviluppatore; i tempi di risposta possono variare.'], emailLabel: 'Invia un’e-mail' },
      { id: 'helpful-details', title: 'Dettagli utili per il supporto', paragraphs: ['Per un problema tecnico, alcuni dettagli rilevanti possono facilitare l’analisi.'], bullets: ['Modello di iPhone o iPad', 'Versione di iOS o iPadOS', 'Versione dell’app Zone', 'Cosa ti aspettavi e cosa è successo'] },
      { id: 'privacy-note', title: 'Prima dell’invio', paragraphs: ['Non includere password, dati di pagamento o altre informazioni molto sensibili. Condividi informazioni su blocchi o cronologia solo se pertinenti e se ti senti a tuo agio.'] }
    ] }
  }
};
