export const ptBR = {
  htmlLang: 'pt-BR', hreflang: 'pt-BR', prefix: 'pt-br', languageName: 'Português (Brasil)', shortLanguage: 'PT', legalLocale: 'pt-br',
  nav: { blocker: 'Bloqueador', how: 'Como funciona', privacy: 'Privacidade', faq: 'Dúvidas', download: 'Baixar Zone', menu: 'Abrir menu', language: 'Idioma', home: 'Início' },
  common: {
    appStore: 'Baixar na App Store', learnMore: 'Veja como o Zone bloqueia distrações', available: 'Para iPhone e iPad · Requer iOS 18 ou posterior', kicker: 'Zone para iPhone e iPad', footerText: 'Bloqueio rigoroso de apps e sites para proteger seu foco.',
    product: 'Produto', guides: 'Guias', company: 'Informações', legalPolicy: 'Política de privacidade completa', copyright: '© 2026 Vikas Saini. Todos os direitos reservados.', appleNote: 'Apple, iPhone, iPad, Tempo de Uso, Dynamic Island e Live Activities são marcas da Apple Inc.',
    skipContent: 'Pular para o conteúdo', primaryNavigation: 'Navegação principal', screenTimeGuide: 'Alternativa ao Tempo de Uso', doomscrollingGuide: 'Parar o doomscrolling', press: 'Imprensa', webAnalytics: ['Analytics do site', 'Este site usa Cloudflare Web Analytics para entender, de forma agregada, visitas, referências, países, dispositivos e desempenho. A Cloudflare declara que o serviço não coleta nem usa dados pessoais dos visitantes e não usa cookies ou localStorage. Isso é separado do app Zone, que não inclui analytics de terceiros.'], onThisPage: 'Nesta página', related: 'Guia relacionado', ctaTitle: 'Faça a próxima hora ser sua.', ctaBody: 'Escolha o que bloquear, inicie o timer e dê um único destino à sua atenção.', factsOnly: 'As informações refletem a versão atual do Zone.'
  },
  home: {
    metaTitle: 'Zone — Bloqueador rigoroso de apps e sites para iPhone', metaDescription: 'Bloqueie apps e sites durante sessões de foco. Zone é um timer rigoroso e privado para iPhone e iPad.', eyebrow: 'Foco rigoroso por design', title: 'Silencie o ruído.', titleAccent: 'Entre na sua zona.', intro: 'Zone é um timer de foco que bloqueia apps e sites no iPhone e iPad, para que um impulso não vire uma hora de rolagem.', secondaryCta: 'Ver como o bloqueio funciona',
    proofOneTitle: 'Modo Estrito', proofOneBody: 'Torna mais difícil abandonar uma sessão', proofTwoTitle: 'Privado por padrão', proofTwoBody: 'Sem conta. Suas escolhas são privadas.',
    signals: [['Apps + sites', 'Bloqueie ambos na mesma sessão'], ['Modo Estrito', 'Adicione atrito quando a vontade falhar'], ['Live Activities', 'Veja o tempo sem reabrir o Zone'], ['Design privado', 'Sem conta nem rastreio publicitário']],
    featureLabel: 'Bloqueio de distrações', featureTitle: 'Um timer que muda o que seu celular pode fazer.', featureIntro: 'Timers comuns apenas contam minutos. Zone combina a contagem regressiva com restrições reais para proteger o tempo que você decidiu dedicar ao foco.',
    blockerTitle: 'Escolha as distrações', blockerBody: 'Selecione os apps e categorias de sites que ficarão indisponíveis. Zone não consegue ver os itens específicos que você escolheu.',
    timerTitle: 'Escolha seu tempo', timerBody: 'Inicie uma sessão predefinida ou personalizada e acompanhe o tempo no Zone, na Tela Bloqueada ou na Dynamic Island.',
    strictTitle: 'Crie compromisso real', strictBody: 'O Modo Estrito foi feito para o momento em que surge a vontade de terminar antes da hora.', strictRows: ['Bloqueio de apps e sites', 'Timers predefinidos ou personalizados', 'Modo Estrito opcional'],
    privacyTitle: 'Foco sem vigilância', privacyBody: 'Zone faz seu trabalho sem criar um perfil publicitário sobre sua atenção.', privacyPoints: ['Sem conta', 'Sem analytics de terceiros', 'Seleções privadas', 'Seu histórico continua seu'],
    flowLabel: 'Como funciona', flowTitle: 'Três passos entre a intenção e o foco.', flow: [['Escolha', 'Selecione os apps e sites que costumam tirar sua atenção.'], ['Comprometa-se', 'Defina a duração e ative o Modo Estrito se precisar de mais atrito.'], ['Concentre-se', 'Zone aplica as restrições e mantém o tempo restante visível.']],
    insightLabel: 'Veja o esforço', insightTitle: 'Transforme minutos de foco em um padrão que você entende.', insightIntro: 'Revise sessões, tempo focado, sequências e tentativas bloqueadas. Você também pode salvar sessões no Apple Health como Mindful Minutes.',
    insightRows: [['Histórico de sessões', 'Veja quando e por quanto tempo você focou.'], ['Sequências e insights', 'Perceba sua consistência sem criar mais ruído.'], ['Apple Health opcional', 'Salve sessões como Mindful Minutes se quiser.']],
    quote: 'Seu celular deve proteger a decisão que você já tomou, não pedir que você a tome de novo.', quoteBy: 'A ideia por trás do Zone', timerAlt: 'Timer de foco do Zone em um iPhone', appPickerAlt: 'Seleção de apps para bloquear no Zone', insightsAlt: 'Insights de sessões de foco no Zone', faqLabel: 'Respostas rápidas', faqTitle: 'Antes de iniciar uma sessão', faqIntro: 'Os detalhes práticos que normalmente você quer saber primeiro.'
  },
  faqs: [
    ['O que o Zone bloqueia?', 'Zone pode restringir apps e sites selecionados enquanto uma sessão está ativa. Os frameworks de Tempo de Uso da Apple aplicam as restrições no aparelho.'],
    ['O Zone consegue ver os apps ou sites que escolho?', 'Não. A Apple fornece seleções opacas, então o Zone aplica suas escolhas sem saber quais apps ou sites específicos foram selecionados.'],
    ['Posso encerrar uma sessão antes?', 'Sessões normais podem ser encerradas. O Modo Estrito torna essa escolha mais difícil; use-o apenas quando aceitar a duração escolhida.'],
    ['O Zone exige uma conta?', 'Não. Você pode usar o Zone sem criar uma conta.'],
    ['Quais aparelhos são compatíveis?', 'Zone está disponível para iPhone e iPad compatíveis com iOS ou iPadOS 18 ou posterior.'],
    ['O Zone funciona com Apple Health?', 'Opcionalmente. Se você permitir, o Zone pode salvar sessões concluídas como Mindful Minutes.'],
    ['Zone é um tratamento para vício?', 'Não. Zone é uma ferramenta de produtividade que adiciona atrito a distrações; não é tratamento médico.']
  ],
  articles: {
    blocker: { metaTitle: 'Bloqueador rigoroso de apps e sites para iPhone — Zone', metaDescription: 'Veja como o Zone bloqueia apps e sites em sessões com timer no iPhone e iPad, com Modo Estrito opcional.', eyebrow: 'Bloqueador de apps e sites', title: 'Deixe as distrações fora de alcance por um tempo.', intro: 'Zone combina um timer de foco com restrições de apps e sites. Você decide o que bloquear, a duração e se quer usar o Modo Estrito.', sections: [
      { id: 'what', title: 'O que o Zone bloqueia', paragraphs: ['Zone pode ocultar apps e sites selecionados enquanto uma sessão está ativa. Escolha redes sociais, vídeos, compras, notícias ou outras opções disponíveis na interface da Apple.'], bullets: ['Apps selecionados no iPhone e iPad', 'Sites e categorias selecionados', 'Combinações salvas como predefinições reutilizáveis'] },
      { id: 'how', title: 'Como o bloqueio funciona no iPhone', paragraphs: ['Zone usa os frameworks de Tempo de Uso da Apple. O sistema fornece uma representação opaca das suas escolhas, permitindo o bloqueio sem revelar os itens específicos.', 'Quando o timer termina, as restrições da sessão são removidas. Zone não precisa ler seu histórico de navegação nem observar os apps que você abre.'] },
      { id: 'strict', title: 'O que muda no Modo Estrito', paragraphs: ['O Modo Estrito adiciona compromisso e torna deliberadamente mais difícil abandonar uma sessão antes da hora. Para sessões flexíveis, deixe-o desligado.'], callout: ['Use de propósito', 'Comece com uma duração realista e aumente apenas quando o padrão funcionar para você.'] },
      { id: 'setup', title: 'Configuração simples', steps: ['Escolha os apps e sites que distraem você.', 'Selecione a duração.', 'Decida se precisa do Modo Estrito.', 'Inicie e deixe o Zone em segundo plano.'] },
      { id: 'privacy', title: 'Bloqueio sem uma lista dos seus hábitos', paragraphs: ['Zone não vê suas escolhas específicas. Não exige conta e não inclui analytics de terceiros. Suas escolhas e seu histórico continuam privados.'] }
    ] },
    screenTime: { metaTitle: 'Uma alternativa ao Tempo de Uso focada em sessões — Zone', metaDescription: 'Compare Zone e Tempo de Uso da Apple para bloqueio com timer, sites, apps, sessões de foco e Modo Estrito.', eyebrow: 'Alternativa ao Tempo de Uso', title: 'Tempo de Uso é amplo. Zone foi feito para uma sessão de foco.', intro: 'Tempo de Uso reúne relatórios, limites e controles familiares. Zone usa os frameworks da Apple para uma tarefa mais específica: proteger um bloco de foco.', sections: [
      { id: 'difference', title: 'A diferença prática', paragraphs: ['Use Tempo de Uso para limites gerais, horários, conteúdo ou família. Use Zone quando quiser escolher distrações, iniciar um timer e focar agora.'], comparison: [['Necessidade', 'Zone', 'Tempo de Uso'], ['Sessões com timer', 'Fluxo principal', 'Por limites e horários'], ['Bloqueio selecionado', 'Por sessão', 'Por limite ou horário'], ['Compromisso rigoroso', 'Modo Estrito opcional', 'Códigos e controles diferentes'], ['Relatórios', 'Sessões e tentativas bloqueadas', 'Atividade geral do aparelho']] },
      { id: 'choose', title: 'Quando o Zone se encaixa melhor', bullets: ['Você quer um ritual claro de início e fim.', 'Quer bloqueio e contagem regressiva juntos.', 'Quer predefinições para trabalho, estudo ou descanso.', 'Quer ver o tempo em Live Activities ou Dynamic Island.'] },
      { id: 'together', title: 'Você pode usar os dois', paragraphs: ['Zone não substitui todos os recursos do Tempo de Uso. Mantenha limites de longo prazo e use Zone para sessões deliberadas.'] },
      { id: 'accurate', title: 'Construído sobre os controles da Apple', paragraphs: ['Zone depende do acesso que você aprova e dos frameworks suportados pela Apple. Não contorna o iOS nem promete um bloqueio que o sistema não pode aplicar.'] }
    ] },
    doomscrolling: { metaTitle: 'Como parar o doomscrolling no iPhone — Guia prático', metaDescription: 'Guia prático para reduzir o doomscrolling no iPhone mudando gatilhos, adicionando atrito e usando bloqueio com timer.', eyebrow: 'Guia prático de foco', title: 'Pare de depender da força de vontade para parar de rolar.', intro: 'O doomscrolling costuma começar com uma ação automática: desbloquear, tocar, atualizar. A intervenção mais útil acontece antes que o ciclo ganhe força.', sections: [
      { id: 'pattern', title: 'Torne o padrão visível', paragraphs: ['Observe o gatilho, não só o total de horas. Talvez você abra um feed depois de uma tarefa difícil, entre atividades, na cama ou após uma notificação.', 'Por um dia, anote o que acontece imediatamente antes. Uma lista curta de gatilhos é mais útil do que se culpar pelo total semanal.'] },
      { id: 'friction', title: 'Adicione atrito antes da primeira rolagem', bullets: ['Tire os apps mais tentadores da primeira tela.', 'Desative notificações que não exigem ação rápida.', 'Saia de serviços que abre automaticamente.', 'Use um bloqueador com timer nos períodos previsíveis.'], callout: ['Por que funciona', 'Você não quer tornar a distração impossível para sempre. Só cria tempo para a escolha consciente alcançar o impulso.'] },
      { id: 'window', title: 'Proteja primeiro uma janela pequena', paragraphs: ['Comece com algo possível: 20 minutos de leitura, 30 de trabalho ou os primeiros 45 minutos do dia. No Zone, bloqueie apenas o que atrapalha essa janela e use o Modo Estrito se quiser compromisso extra.'] },
      { id: 'replace', title: 'Dê outro destino ao impulso', paragraphs: ['Bloquear remove uma opção, mas não escolhe a próxima. Deixe a tarefa, o documento ou o livro visível antes de começar.'] },
      { id: 'review', title: 'Revise o padrão, não seu valor', paragraphs: ['No fim da semana, veja quais janelas funcionaram e ajuste o ambiente ou a duração. É um problema de design, não um julgamento pessoal.', 'Se o uso causar perigo ou sofrimento sério, um app de produtividade não substitui apoio profissional qualificado.'] }
    ] },
    faq: { metaTitle: 'Dúvidas sobre Zone — Bloqueio, Modo Estrito e privacidade', metaDescription: 'Respostas sobre bloqueio de apps e sites, Modo Estrito, privacidade, Live Activities e Apple Health.', eyebrow: 'Perguntas frequentes', title: 'Respostas claras antes de bloquear distrações.', intro: 'Como o Zone funciona, o que ele acessa e o que esperar de uma sessão.', sections: [] },
    privacy: { metaTitle: 'Privacidade do Zone — Bloqueio sem conta', metaDescription: 'Resumo claro sobre seleções de bloqueio, histórico, Apple Health, iCloud e dados de Live Activities no Zone.', eyebrow: 'Resumo de privacidade', title: 'Suas escolhas de foco devem continuar suas.', intro: 'Zone bloqueia distrações sem conhecer sua lista privada de apps e sites.', sections: [
      { id: 'summary', title: 'Em resumo', bullets: ['Nenhuma conta é necessária.', 'Zone não vê os apps ou sites específicos selecionados.', 'Seu histórico e suas escolhas continuam privados.', 'O app não inclui analytics de terceiros nem rastreadores publicitários.'] },
      { id: 'screen-time', title: 'Seleções do Tempo de Uso', paragraphs: ['A Apple fornece tokens opacos. Zone os usa para aplicar restrições, mas eles não revelam suas escolhas ao desenvolvedor.'] },
      { id: 'health', title: 'Apple Health', paragraphs: ['Salvar sessões como Mindful Minutes é opcional. Zone pede acesso apenas se você ativar o recurso, e a permissão continua sob seu controle no iOS.'] },
      { id: 'icloud', title: 'Sincronização privada com iCloud', paragraphs: ['O Zone Sync armazena seu histórico de foco e as preferências compatíveis apenas na sua conta privada do iCloud. O Zone não envia esses dados para um servidor externo. Isso permite restaurá-los após reinstalar o Zone e mantê-los nos dispositivos com a mesma Conta Apple.'] },
      { id: 'live', title: 'Live Activities', paragraphs: ['Se você ativar atualizações remotas, Zone envia o token APNs e o estado mínimo do timer necessário. Sua seleção de apps e sites não é enviada.'] },
      { id: 'policy', title: 'Leia a política completa', paragraphs: ['Este resumo não substitui a política jurídica. A política já publicada continua sendo o documento oficial.'], link: ['Abrir a política de privacidade completa', 'legal'] }
    ] },
    press: { metaTitle: 'Kit de imprensa do Zone — Informações e capturas', metaDescription: 'Informações do produto, link da App Store, desenvolvedor e recursos oficiais para conhecer e apresentar o Zone.', eyebrow: 'Imprensa e avaliações', title: 'Os fatos essenciais sobre o Zone.', intro: 'Uma referência curta e precisa para jornalistas, avaliadores e criadores.', sections: [
      { id: 'summary', title: 'Resumo do produto', paragraphs: ['Zone: App Blocker & Focus é um app de produtividade para iPhone e iPad do desenvolvedor independente Vikas Saini. Diferente de um timer que apenas conta o tempo, o Zone pode restringir apps e sites selecionados durante uma sessão. O Modo Estrito opcional acrescenta compromisso, enquanto Live Activities, Dynamic Island e insights privados ajudam a manter o foco.'] },
      { id: 'facts', title: 'Informações rápidas', facts: [['Produto', 'Zone: App Blocker & Focus'], ['Desenvolvedor', 'Vikas Saini'], ['Plataformas', 'iPhone e iPad'], ['Requisito', 'iOS ou iPadOS 18 ou posterior'], ['Categoria', 'Produtividade'], ['Conta', 'Não é necessária']] },
      { id: 'angles', title: 'O que diferencia o Zone', bullets: ['Timer e bloqueador funcionam como uma única sessão.', 'O Modo Estrito adiciona fricção quando não deve ser fácil abandonar a sessão.', 'A Apple fornece seleções opacas: o Zone e o desenvolvedor não veem os apps ou sites específicos.', 'Live Activities e Dynamic Island mantêm a contagem visível sem reabrir o app.'] },
      { id: 'assets', title: 'Recursos oficiais', paragraphs: ['O ícone e as capturas localizadas podem ser usados ao cobrir ou avaliar Zone com precisão. Não altere o ícone nem sugira endosso.'], downloads: [['Ícone do app', 'app-icon.png'], ['Captura do timer', 'timer.png'], ['Captura da seleção de apps', 'app-picker.png'], ['Captura de insights', 'insights.png']], downloadLabel: 'Baixar PNG', link: ['Ver Zone na App Store', 'appstore'] },
      { id: 'contact', title: 'Contato', paragraphs: ['Para dúvidas sobre o produto, acesso para avaliações, entrevistas ou imprensa, fale diretamente com o desenvolvedor.'], emailLabel: 'Enviar e-mail ao desenvolvedor' }
    ] },
    contact: { metaTitle: 'Contato do Zone — Suporte, sugestões e imprensa', metaDescription: 'Fale com o desenvolvedor independente do Zone para suporte, sugestões, feedback, avaliações ou imprensa.', eyebrow: 'Contato do Zone', title: 'Tem uma dúvida, sugestão ou comentário?', intro: 'Fale com o desenvolvedor independente do Zone para suporte, sugestões, avaliações, imprensa ou outras questões sobre o produto.', sections: [
      { id: 'email', title: 'Envie um e-mail ao Zone', paragraphs: ['Envie sua mensagem para o endereço abaixo. As mensagens são analisadas pelo desenvolvedor; o tempo de resposta pode variar.'], emailLabel: 'Enviar e-mail' },
      { id: 'helpful-details', title: 'Informações úteis para suporte', paragraphs: ['Para um problema técnico, alguns detalhes relevantes podem facilitar a investigação.'], bullets: ['Modelo do iPhone ou iPad', 'Versão do iOS ou iPadOS', 'Versão do app Zone', 'O que você esperava e o que aconteceu'] },
      { id: 'privacy-note', title: 'Antes de enviar', paragraphs: ['Não inclua senhas, dados de pagamento ou outras informações altamente confidenciais. Compartilhe informações sobre bloqueios ou histórico somente quando forem relevantes e você se sentir confortável.'] }
    ] }
  }
};
